### ISSUE TITLE
Media Queries are deleted

### ISSUE THREAD

**Issue by zokkis** [PlayForm/Compress#253] opened 2023-12-31 16:58 UTC
All of my media queries are deleted after adding astro-compress

**Comment by NikolaRHristov** [comment] 2024-01-01 13:00
Hi, can you provide a minimum viable reproduction, maybe on [Stackblitz](https://stackblitz.com/) or [CodeSandbox](https://codesandbox.io/)?

**Comment by gitZokki** [comment] 2024-01-01 14:01
I dont know why, but I cant reproduce it with a new install.
But I can reproduce it on my project, even tho I run npm i and npm ci and disabled all the other integrations, but on my project is still the error

"@astrojs/check": "^0.3.4",
"@astrojs/mdx": "^2.0.3",
"astro": "^4.0.7",
"astro-compress": "astro-community/AstroCompress#no-sharp",
"astro-purgecss": "^4.0.0",
"node-html-parser": "^6.1.12",
"purgecss": "^5.0.0",
"sass": "^1.69.5",
"sharp": "^0.33.1",
"typescript": "^5.3.3"

astro-integrations (as I said, I tried to disable and still same problem)
purgecss({ variables: true }),
compress({ Image: false }),
mdx()

tsconfig
{
	"extends": "astro/tsconfigs/strictest",
	"compilerOptions": {
		"baseUrl": ".",
		"paths": {
			"@/*": ["./*"],
			"@public/*": ["./public/*"],
			"@src/*": ["./src/*"],
			"@components/*": ["./src/components/*"],
			"@i18n/*": ["./src/i18n/*"],
			"@layouts/*": ["./src/layouts/*"],
			"@pages/*": ["./src/pages/*"],
			"@shared/*": ["./src/shared/*"],
			"@styles/*": ["./src/styles/*"]
		}
	}
}

**Comment by NikolaRHristov** [comment] 2024-01-01 14:18
`astro-purgecss` could be removing some of your CSS, have you tried running without it?

**Comment by gitZokki** [comment] 2024-01-02 20:32
> disabled all the other integrations, but on my project is still the error

So, yes I tried without any other integrations and I reinstalled Ubuntu and same problem

**Comment by NikolaRHristov** [comment] 2024-05-09 17:21
Should be fixed in the latest `astro-compress` [v2.2.23](https://github.com/PlayForm/Compress/releases/tag/AstroCompress%2Fv2.2.23) and `@playform/compress` [v0.0.4](https://github.com/PlayForm/Compress/releases/tag/Compress%2Fv0.0.4)

**Closed** 2024-05-09 20:15 UTC
